Support open mail app
authgear/authgear-sdk-android pull request #118
Opened 2023-01-17 08:21 UTC by tung2744

ref https://github.com/authgear/authgear-server/issues/2785

![Screenshot_1673943550](https://user-images.githubusercontent.com/34942210/212845456-a0e4f666-73ea-4ddd-a14e-4ee39050feeb.png)

2023-01-17 11:57 UTC, tung2744 commented
@louischan-oursky Updated, thanks!

2023-01-18 03:26 UTC, louischan-oursky requested changes

2023-01-18 03:26 UTC, louischan-oursky commented on sdk/src/main/java/com/oursky/authgear/EmailClient.kt
> +        @JvmStatic val gmail = EmailClient("com.google.android.gm")
Constants should be named in UPPER_SNAKE_CASE. See https://kotlinlang.org/docs/coding-conventions.html#property-names

2023-01-18 03:26 UTC, louischan-oursky commented on javasample/src/main/java/com/oursky/authgeartest/MainViewModel.java
> +                Intent intent = Authgear.Companion.makeEmailClientIntentChooser(
Authgear.Companion does not follow Java's convention. Add `@JvmField` to makeEmailClientIntentChooser to make it directly accessible under Authgear.

2023-01-18 05:53 UTC, tung2744 commented
@louischan-oursky Updated, thanks!

2023-01-30 02:09 UTC, merged